# Generated by Django 5.1.1 on 2024-09-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_snippet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='public_snippet',
            field=models.BooleanField(default=True),
        ),
    ]
